### ISSUE TITLE
Frida error?

### ISSUE THREAD

**Issue by InvalidUUID** [cursey/kanan#153]
Getting this error whenever I try to install kanan on a new pc, for some reason.. I don't understand what im doing wrong because it worked just fine on my own pc.

Java is installed properly, and I made sure to install the latest version of Python x64 and Frida, also using the latest repo of kanan (updated today, Jan 18).

See this video for the error, also picture down bellow. 
![Image of Error](http://puu.sh/trw4f/cbcbc5018c.png)

https://youtu.be/DAfgBWHh3Ng

**Comment by ruuka** [comment]
I have the exact same problem right now, hopefully someone could take a look into it !

**Comment by cursey** [comment]
I believe this is an issue with the latest version of frida, and not kanan. Please open a console and type `pip install frida==9.0.7` to install the previous version of frida and let me know if it fixes this issue.

**Comment by InvalidUUID** [comment]
![Image of Error](http://puu.sh/trxC7/cbc2e82c3e.png)
With 9.0.7 Frida installed (uninstalled old version before installing new one)

**Comment by cursey** [comment]
Do you have the most recent version of the kanan files? I thought I fixed this in a recent commit (see #152 and commits d1d530c / b99008d).

**Comment by InvalidUUID** [comment]
Oh right, forgot I used an older version to see if it wasnt kanan, didnt update back to latest.
Still getting a few errors with new one but it seems to run, mostly.
![kanangif](https://puu.sh/trxY7/27dfab1611.gif)

**Comment by cursey** [comment]
Yep, the latest patch broke a few things. I've already started fixing them but I'm glad its mostly working for you like it should.

**Comment by InvalidUUID** [comment]
Well thanks for the quick reply even though its late asfk

**Comment by ruuka** [comment]
Thanks to both of you! Fixed for me as well as I had the same exact issues.
